"""In-repository synthetic DGPs. No observational files.

What problem is being solved?
    Supply small arrays whose generating process is known, so that a
    training run can be interpreted as behaviour under that process.

What assumptions are required?
    Draws are iid given the documented parameters. Two-moons and Gaussian
    mixtures are two-dimensional binary classification problems. Motif
    sequences plant a length-3 pattern in Gaussian noise. Imbalance is a
    5%/95% mixture unless the caller changes prevalence.

Why was this method chosen?
    Known labels and known class-conditional distributions make failure
    modes (majority-class CE, dead ReLU) identifiable. Nothing is downloaded.

What alternative method could have been used?
    Public tabular datasets; pretrained embeddings; image benchmarks.

What can go wrong?
    Treating a two-moons accuracy as evidence about a real population.
    A motif DGP that is linearly separable in the flattened sequence
    without using the convolution at all — the CNN is still a restricted
    hypothesis class, not a uniqueness claim.

How is correctness independently checked?
    Tests check shapes, label sets, planted-motif presence, and that the
    Dataset helper's train indices are disjoint from test indices.

What can legitimately be concluded?
    These arrays were generated by the stated procedures.

What cannot be concluded?
    Anything about a natural dataset, a production model, or a causal effect.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray

from dllab._rng import get_rng


@dataclass(frozen=True)
class ClassificationBatch:
    x: NDArray[np.floating]
    y: NDArray[np.integer]


def two_moons(
    n: int = 80,
    noise: float = 0.12,
    seed: int | np.random.Generator | None = 2026,
) -> ClassificationBatch:
    """Two interleaving half-circles in R^2. Labels in {0, 1}."""
    if n < 2:
        raise ValueError("n must be at least 2")
    if noise < 0.0:
        raise ValueError("noise must be non-negative")
    rng = get_rng(seed)
    n0 = n // 2
    n1 = n - n0
    theta0 = rng.uniform(0.0, np.pi, size=n0)
    theta1 = rng.uniform(0.0, np.pi, size=n1)
    x0 = np.stack([np.cos(theta0), np.sin(theta0)], axis=1)
    x1 = np.stack([1.0 - np.cos(theta1), 1.0 - np.sin(theta1) - 0.5], axis=1)
    x = np.concatenate([x0, x1], axis=0)
    x = x + rng.normal(scale=noise, size=x.shape)
    y = np.concatenate([np.zeros(n0, dtype=int), np.ones(n1, dtype=int)])
    perm = rng.permutation(n)
    return ClassificationBatch(x=x[perm], y=y[perm])


def gaussian_mixture(
    n: int = 80,
    seed: int | np.random.Generator | None = 2026,
) -> ClassificationBatch:
    """Two isotropic Gaussians in R^2, well separated."""
    if n < 2:
        raise ValueError("n must be at least 2")
    rng = get_rng(seed)
    n0 = n // 2
    n1 = n - n0
    x0 = rng.normal(loc=(-1.6, -1.6), scale=0.35, size=(n0, 2))
    x1 = rng.normal(loc=(1.6, 1.6), scale=0.35, size=(n1, 2))
    x = np.concatenate([x0, x1], axis=0)
    y = np.concatenate([np.zeros(n0, dtype=int), np.ones(n1, dtype=int)])
    perm = rng.permutation(n)
    return ClassificationBatch(x=x[perm], y=y[perm])


def linearly_separable(
    n: int = 40,
    seed: int | np.random.Generator | None = 2026,
) -> ClassificationBatch:
    """Half-plane labels with a margin. Used to check that CE can decrease."""
    if n < 2:
        raise ValueError("n must be at least 2")
    rng = get_rng(seed)
    x = rng.normal(scale=0.4, size=(n, 2))
    x[n // 2 :, 0] += 2.2
    x[n // 2 :, 1] += 2.2
    y = np.zeros(n, dtype=int)
    y[n // 2 :] = 1
    perm = rng.permutation(n)
    return ClassificationBatch(x=x[perm], y=y[perm])


def imbalanced_gaussian(
    n: int = 200,
    prevalence: float = 0.05,
    mean_shift: float = 1.8,
    seed: int | np.random.Generator | None = 2026,
) -> ClassificationBatch:
    """Rare class has a mean shift on x[:, 0]. Default prevalence 5%."""
    if n < 2:
        raise ValueError("n must be at least 2")
    if not 0.0 < prevalence < 1.0:
        raise ValueError("prevalence must lie in (0, 1)")
    rng = get_rng(seed)
    y = (rng.random(n) < prevalence).astype(int)
    x = rng.normal(size=(n, 2))
    x[y == 1, 0] += mean_shift
    return ClassificationBatch(x=x, y=y)


MOTIF = np.array([1.0, -1.0, 1.0], dtype=float)


def motif_sequences(
    n: int = 60,
    length: int = 16,
    noise: float = 0.25,
    seed: int | np.random.Generator | None = 2026,
) -> ClassificationBatch:
    """1-D sequences. Class 1 plants ``MOTIF`` at a random valid index.

    x has shape (n, 1, length) so that it can be fed to Conv1d directly.
    Flattening would hide the local receptive field; the CNN keeps it.
    """
    if n < 2:
        raise ValueError("n must be at least 2")
    if length < MOTIF.size:
        raise ValueError("length must be at least the motif length")
    if noise < 0.0:
        raise ValueError("noise must be non-negative")
    rng = get_rng(seed)
    n1 = n // 2
    x = rng.normal(scale=noise, size=(n, 1, length))
    y = np.zeros(n, dtype=int)
    max_start = length - MOTIF.size + 1
    for i in range(n1):
        start = int(rng.integers(0, max_start))
        x[i, 0, start : start + MOTIF.size] += MOTIF
        y[i] = 1
    perm = rng.permutation(n)
    return ClassificationBatch(x=x[perm], y=y[perm])
